{% set version = "0.3.21" %}

package:
  name: openblas_multipkg
  version: {{ version }}

source:
  fn: openblas-{{ version }}.tar.gz
  url: https://github.com/xianyi/OpenBLAS/archive/v{{ version }}.tar.gz
  sha256: f36ba3d7a60e7c8bcc54cd9aaa9b1223dd42eaf02c811791c37e8ca707c241ca
    # new in 0.3 series
    # requires glibc >=2.21; disable for the foreseeable future.
    #   https://github.com/xianyi/OpenBLAS/blob/dbfd7524cd94fe15930ed2f78b7789f15b22fec0/Makefile.rule#L112-L116
    # Also, see # https://github.com/xianyi/OpenBLAS/issues/1761
    # - 0003-turn-TLS-off.patch
    #- gh2111.patch

build:
  number: 1
  missing_dso_whitelist:
    # Mildly concerned this triggers an overlinking warning, but it may be a
    # sign some S390X-specific changes needed in conda-build.  Leaving this in
    # while we investigate so the linux-s390x build out can continue.
    - "*/ld64.so.1"   # [s390x]

requirements:
  build:
    - {{ compiler("c") }}      #[ppc_arch != 'p10']
    - {{ compiler("fortran") }}          #[ppc_arch != 'p10']
    - perl
    - cmake                      # [win]
    - curl                       # [win]
    - jom                        # [win]
    - make                       # [linux]
    - patch                      # [linux]
    - llvm-openmp
    - libgcc-ng {{ libgcc }}            #[cudatoolkit == "11.2"]
    - libstdcxx-ng {{ libstdcxx }}      #[cudatoolkit == "11.2"]
    - libgfortran-ng {{ libgfortran }}  #[cudatoolkit == "11.2"]
  host:
    - libgcc-ng {{ libgcc }}            #[cudatoolkit == "11.2"]
    - libstdcxx-ng {{ libstdcxx }}      #[cudatoolkit == "11.2"]
    - libgfortran-ng {{ libgfortran }}  #[cudatoolkit == "11.2"]

outputs:
  - name: libopenblas
    files:
      - lib/libblas{{ SHLIB_EXT }}    # [linux]
      - lib/libcblas{{ SHLIB_EXT }}   # [linux]
      - lib/liblapack{{ SHLIB_EXT }}  # [linux]
      - lib/libopenblas*.so*          # [linux]
    requirements:
      build:
        - {{ compiler("c") }}           #[ppc_arch != 'p10']
        - {{ compiler("fortran") }}     #[ppc_arch != 'p10']
        - llvm-openmp
        - libgcc-ng {{ libgcc }}        #[cudatoolkit == "11.2"]
        - libstdcxx-ng {{ libstdcxx }}  #[cudatoolkit == "11.2"]
        - libgfortran-ng {{ libgfortran }}   #[cudatoolkit == "11.2"]
      host:
        - libgcc-ng {{ libgcc }}        #[cudatoolkit == "11.2"]
        - libstdcxx-ng {{ libstdcxx }}  #[cudatoolkit == "11.2"]
        - libgfortran-ng {{ libgfortran }}   #[cudatoolkit == "11.2"]
      run:
        - libgfortran-ng {{ libgfortran }}   #[cudatoolkit == "11.2"]
        - libgfortran-ng         #[c_compiler_version == "11.2.*"]

    test:
      requires:
        - python {{ python }}      # [linux]
      commands:
        - python -c "import ctypes; ctypes.cdll['${PREFIX}/lib/libopenblas${SHLIB_EXT}']"  # [linux]
    about:
      home: http://www.openblas.net/
      license: BSD-3-clause
      license_family: BSD
      license_file: LICENSE
      summary: An Optimized BLAS library
      description: OpenBLAS is based on GotoBLAS2 1.13 BSD version.
      doc_url: http://www.openblas.net/
      doc_source_url: https://github.com/xianyi/OpenBLAS/blob/develop/README.md
      dev_url: https://github.com/xianyi/OpenBLAS

  - name: libopenblas-static
    files:
      - lib/libblas.a
      - lib/libcblas.a
      - lib/liblapack.a
      - lib/libopenblas*.a
    test:
      commands:
        - test -f ${PREFIX}/lib/libopenblas.a                            # [unix]
    about:
      home: http://www.openblas.net/
      license: BSD-3-clause
      license_family: BSD
      license_file: LICENSE
      summary: OpenBLAS static libraries.
      description: OpenBLAS is based on GotoBLAS2 1.13 BSD version.
      doc_url: http://www.openblas.net/
      doc_source_url: https://github.com/xianyi/OpenBLAS/blob/develop/README.md
      dev_url: https://github.com/xianyi/OpenBLAS

  - name: openblas-devel
    files:
      - include/cblas.h
      - include/f77blas.h
      - include/lapacke*.h
      - include/openblas_config.h
      - lib/cmake/openblas
      - lib/pkgconfig/blas.pc
      - lib/pkgconfig/cblas.pc
      - lib/pkgconfig/lapack.pc
      - lib/pkgconfig/openblas.pc
      - site.cfg
    run_exports:
      - {{ pin_subpackage("libopenblas") }}
      - blas * openblas
    requirements:
      build:
        - libgcc-ng {{ libgcc }}            #[cudatoolkit == "11.2"]
        - libstdcxx-ng {{ libstdcxx }}      #[cudatoolkit == "11.2"]
        - libgfortran-ng {{ libgfortran }}  #[cudatoolkit == "11.2"]
      host:
        - libgcc-ng {{ libgcc }}            #[cudatoolkit == "11.2"]
        - libstdcxx-ng {{ libstdcxx }}      #[cudatoolkit == "11.2"]
        - libgfortran-ng {{ libgfortran }}  #[cudatoolkit == "11.2"]
      run:
        - {{ pin_subpackage("libopenblas", exact=True) }}
        - {{ pin_subpackage("nomkl", exact=True) }}
    about:
      summary: OpenBLAS headers and libraries for developing software that used OpenBLAS.

  # openblas meta-package. It is better to require openblas-devel or libopenblas
  - name: openblas
    requirements:
      run:
        - {{ pin_subpackage("libopenblas", exact=True) }}
        - {{ pin_subpackage("openblas-devel", exact=True) }}
        - {{ pin_subpackage("blas", exact=True) }}
        - {{ pin_subpackage("nomkl", exact=True) }}

    about:
      home: http://www.openblas.net/
      license: BSD-3-clause
      license_family: BSD
      license_file:
        - LICENSE
        - lapack-netlib/LICENSE
      summary: An optimized BLAS library
      description: OpenBLAS is based on GotoBLAS2 1.13 BSD version.
      doc_url: http://www.openblas.net/
      doc_source_url: https://github.com/xianyi/OpenBLAS/blob/develop/README.md
      dev_url: https://github.com/xianyi/OpenBLAS

  # mutex package to keep only one blas implementation in a given env
  - name: blas
    version: 1.0
    build:
      string: openblas
      # track_features doesn't really track anything anymore (blas metapackage
      # dependencies do the same job better). This is still here, though, as it
      # effectively "weighs down" nomkl packages, allowing mkl to take
      # precedence when defaults is the top channel priority.
      track_features:
        - nomkl

  - name: nomkl
    version: 3.0
    build:
      number: 0
    requirements:
      run:
        - blas * openblas
    about:
      license: BSD

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team  
